In [ ]:
import pandas as pd
import numpy as np
import random as rn
import functools
import re

**Find any matching value**

In [ ]:
users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa']
}) 
print(users)
print('\nFinding Montreal in any cell :')
print(users[users.eq('Montreal').any(1)])

    name      city
0  kevin   Toronto
1  james  Montreal
2  kumar   Calgary
3  kevin  Montreal
4  kevin  Montreal
5  james    Ottawa

Finding Montreal in any cell :
    name      city
1  james  Montreal
3  kevin  Montreal
4  kevin  Montreal


**Clean URL in Pandas String (remove string after specific item)**

In [ ]:
df = pd.DataFrame({
    'url': ['https://www.abc.com/page/2/unit234', 'https://www.abc.com/page/3/unit34', 'https://www.abc.com/page/4/unit89']
})
print(df)
df['url'] = df['url'].str.replace('\/unit.*', '/', regex=True)
print('\nAfer removing unit and future chars:')
print(df)

                                  url
0  https://www.abc.com/page/2/unit234
1   https://www.abc.com/page/3/unit34
2   https://www.abc.com/page/4/unit89

Afer removing unit and future chars:
                           url
0  https://www.abc.com/page/2/
1  https://www.abc.com/page/3/
2  https://www.abc.com/page/4/


**Cumulative sum with group by with multiple values**

In [ ]:
df = pd.DataFrame({
    'City': ['Toronto', 'Toronto', 'Toronto', 'Montreal', 'Montreal', 'Montreal', 'New York', 'Toronto', 'New York', 'New York'], 
    'Year': [2020, 2020, 2018, 2018, 2018, 2012, 2012, 2012, 2016, 2018], 
    'Points': [1000, 2000, 3000, 3000, 2000, 1500, 1500, 500, 500, 300]
})
print(df)
df.sort_values(['City', 'Year'], inplace=True)
print('\nAfter Sorting:')
print(df)

df['Points_cum'] = df.groupby(['City', 'Year'])['Points'].cumsum()
print('\nAfter Cumulative Sum:')
print(df)

       City  Year  Points
0   Toronto  2020    1000
1   Toronto  2020    2000
2   Toronto  2018    3000
3  Montreal  2018    3000
4  Montreal  2018    2000
5  Montreal  2012    1500
6  New York  2012    1500
7   Toronto  2012     500
8  New York  2016     500
9  New York  2018     300

After Sorting:
       City  Year  Points
5  Montreal  2012    1500
3  Montreal  2018    3000
4  Montreal  2018    2000
6  New York  2012    1500
8  New York  2016     500
9  New York  2018     300
7   Toronto  2012     500
2   Toronto  2018    3000
0   Toronto  2020    1000
1   Toronto  2020    2000

After Cumulative Sum:
       City  Year  Points  Points_cum
5  Montreal  2012    1500        1500
3  Montreal  2018    3000        3000
4  Montreal  2018    2000        5000
6  New York  2012    1500        1500
8  New York  2016     500         500
9  New York  2018     300         300
7   Toronto  2012     500         500
2   Toronto  2018    3000        3000
0   Toronto  2020    1000        1000
1   Toron

**Append series to existing Dataframe**

In [ ]:
df = pd.DataFrame([1, 3, 4, 5], columns=["id"])
df.set_index("id")
print(df)

marks = pd.Series([79, 20, 45, 99])
df["marks"] = marks
print('\nAfter:')
print(df)

   id
0   1
1   3
2   4
3   5

After:
   id  marks
0   1     79
1   3     20
2   4     45
3   5     99


**Compare two dataframes**

In [ ]:
df1 = pd.DataFrame({
    'a' : [1,2,3], 
    'b' : [9,8,7]
})

df2 = pd.DataFrame({
    'a' : [1,1,3], 
    'b' : [12,8,12]
})

print(df1.compare(df2))

     a          b      
  self other self other
0  NaN   NaN  9.0  12.0
1  2.0   1.0  NaN   NaN
2  NaN   NaN  7.0  12.0


**Difference between datetime by only seconds or dates**

In [ ]:
df1 = pd.to_datetime('2020-10-14 14:52:21')
df2 = pd.to_datetime('2020-10-18 15:58:10')

delta = (df2 - df1)

print('days   : ', delta.days)
print('seconds: ', delta.seconds)

days   :  4
seconds:  3949


**Get dates and delta days in Dataframe**

In [ ]:
entries_count = 6
date_series = pd.Series(pd.date_range('2020-09-01', periods = entries_count, freq = 'D'))
df = pd.DataFrame({'entry_date': date_series})
print(df)

  entry_date
0 2020-09-01
1 2020-09-02
2 2020-09-03
3 2020-09-04
4 2020-09-05
5 2020-09-06


**Get dates and delta days in Dataframe**

In [ ]:
entries_count = 5

date_series = pd.Series(pd.date_range('2020-09-01', periods = entries_count, freq = 'D'))

time_delta_series = pd.Series([pd.Timedelta(days = i) for i in range(entries_count)])

df = pd.DataFrame({'entry_date': date_series, 'delta_days': time_delta_series})

print(df)

  entry_date delta_days
0 2020-09-01     0 days
1 2020-09-02     1 days
2 2020-09-03     2 days
3 2020-09-04     3 days
4 2020-09-05     4 days


**Date addition with time delta**

In [ ]:
date_series = pd.Series(pd.date_range('2020-09-01', periods = entries_count, freq = 'D'))
time_delta_series = pd.Series([pd.Timedelta(days = i) for i in range(entries_count)])
df = pd.DataFrame({'entry_date': date_series, 'delta_days': time_delta_series})
print('\nBefore:')
print(df)

df['new_entry_date'] = df['entry_date'] + df['delta_days']
print('\nAfter:')
print(df)


print('\nData types:')
print(df.dtypes)


Before:
  entry_date delta_days
0 2020-09-01     0 days
1 2020-09-02     1 days
2 2020-09-03     2 days
3 2020-09-04     3 days
4 2020-09-05     4 days

After:
  entry_date delta_days new_entry_date
0 2020-09-01     0 days     2020-09-01
1 2020-09-02     1 days     2020-09-03
2 2020-09-03     2 days     2020-09-05
3 2020-09-04     3 days     2020-09-07
4 2020-09-05     4 days     2020-09-09

Data types:
entry_date         datetime64[ns]
delta_days        timedelta64[ns]
new_entry_date     datetime64[ns]
dtype: object


**Converting Pandas innner list to numpy array without the word `list`**

In [ ]:
s = pd.Series([[1, 2, 3], np.array([1, 2, 3])])
    
print('Original Series:')
print(s)  

arr = np.array(s)
print('\nSeries to Array:')
print(arr)

print('\nAfter converting inner elements to list:')
x = np.array(s[:].tolist())
print(x)

Original Series:
0    [1, 2, 3]
1    [1, 2, 3]
dtype: object

Series to Array:
[list([1, 2, 3]) array([1, 2, 3])]

After converting inner elements to list:
[[1 2 3]
 [1 2 3]]


**Group by multiple columns**

In [ ]:
df.groupby(['county', 'first_name']).sum().sample(5)

**Convert country in Dataframe**

In [ ]:
import country_converter as coco
import pandas as pd

df = pd.DataFrame({'code': ['IN', 'USA', 'BR', 'CAN']})

print('Before:')
print(df)

df['country'] = df.code.apply(lambda x: coco.convert(names = x, to = 'name_short', not_found = None))

print('\nAfter:')
print(df)

Before:
  code
0   IN
1  USA
2   BR
3  CAN

After:
  code        country
0   IN          India
1  USA  United States
2   BR         Brazil
3  CAN         Canada


In [ ]:
!pip install country_converter

     |████████████████████████████████| 51kB 4.3MB/s 
  Created wheel for country-converter: filename=country_converter-0.7.1-cp36-none-any.whl size=50807 sha256=ae2423126e0cfe50bba40e6040d59d69a6ab0d5a55bd14724e18d114a37c8739
  Stored in directory: /root/.cache/pip/wheels/75/be/cb/3c8d07bca8f2c0670e996a174fed372585b32d3aa03f40996a
Successfully built country-converter


**Get a single value by iat**

In [ ]:
df = pd.DataFrame(np.random.randint(0, 100, size = (7, 2)), columns = list('ab'))

print('\nOriginal Dataframe:')
print(df)

val = df.iat[3, 1]

print('\nGetting value at 3rd row and first col:')
print(val)


Original Dataframe:
    a   b
0  14  73
1  14  58
2  49  10
3  87  33
4  10  82
5  66  26
6  74  10

Getting value at 3rd row and first col:
33


**Get last n elements**

In [ ]:
df = pd.DataFrame(np.random.randint(0, 100, size = (7, 2)), columns = list('ab'))

print('\nOriginal Dataframe:')
print(df)

tail_df = df.tail(3)

print('\nLast 3 rows:')
print(tail_df)


Original Dataframe:
    a   b
0   0  51
1  52  63
2  67  46
3   3  34
4  20  53
5  72  93
6  87  69

Last 3 rows:
    a   b
4  20  53
5  72  93
6  87  69


**Add data one by one by using loc function**

In [ ]:
df = pd.DataFrame(columns = ['rows', 'cols', 'time taken'])

df.loc['Dataset1 - Dask'] = (1000, 20, 10)
df.loc['Dataset1 - Pandas'] = (1000, 20, 15)

df

rows cols time taken
Dataset1 - Dask    1000   20         10
Dataset1 - Pandas  1000   20         15

**read_sql in Pandas**

In [ ]:
import sqlite3 as sql

conn = sql.connect('/kaggle/input/rj-sample-datasets/sample.db')

demo_df = pd.read_sql('SELECT ID, NAME FROM DEMO', conn)

print(demo_df)

**Pandas and Numpy Repeat**

In [ ]:
df = pd.DataFrame({
     "entry" : np.repeat(3, 7) # Repeat the number for 7 times
})

print(df)

   entry
0      3
1      3
2      3
3      3
4      3
5      3
6      3


**Pandas and Date with Range**

In [ ]:
import datetime as dt

pd.np.random.seed(0)

df = pd.DataFrame({
     "date" : [dt.date(2012, x, 1) for x in range(1, 11)]
})

print(df)

         date
0  2012-01-01
1  2012-02-01
2  2012-03-01
3  2012-04-01
4  2012-05-01
5  2012-06-01
6  2012-07-01
7  2012-08-01
8  2012-09-01
9  2012-10-01


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  This is separate from the ipykernel package so we can avoid doing imports until


**Simple Dataframe with NaN**

In [ ]:
df = pd.DataFrame([np.nan] * 5)
print(df)

    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN


**Dataframe with NaN**

In [ ]:
df = pd.DataFrame(np.nan, index = [0, 1, 2], columns = ['A', 'B', 'C'])
print(df)

    A   B   C
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN


**iterrows as tuples**

In [ ]:
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 

print(users)  

print('\nIterate rows as tuples:')
for row in users.itertuples():
    print(row)

   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8

Iterate rows as tuples:
Pandas(Index=0, id=1, city='Toronto', count=7)
Pandas(Index=1, id=1, city='Montreal', count=8)
Pandas(Index=2, id=2, city='Calgary', count=9)
Pandas(Index=3, id=2, city='Montreal', count=2)
Pandas(Index=4, id=3, city='Montreal', count=7)
Pandas(Index=5, id=3, city='Ottawa', count=8)


**Apply a custom function on multiple columns**

In [ ]:
amounts = pd.DataFrame({
    "CIBC": [200, 4200, 300, 300], 
    "TD": [1200, 800, 4000, 2000]
})

print('Original Dataframe: ')
print(amounts)

def get_total_amount(x):
    
    # if the amount is less than 500, skip it
    total_amount = 0
    
    if(x['CIBC'] > 499):
        total_amount += x['CIBC']
        
    if(x['TD'] > 499):
        total_amount += x['TD']
    
    return total_amount

amounts['Total'] = amounts.apply(get_total_amount, axis = 1)

print('Dataframe after applying the custom function: ')
print(amounts)

Original Dataframe: 
   CIBC    TD
0   200  1200
1  4200   800
2   300  4000
3   300  2000
Dataframe after applying the custom function: 
   CIBC    TD  Total
0   200  1200   1200
1  4200   800   5000
2   300  4000   4000
3   300  2000   2000


**Exclude specific matching**

In [ ]:
users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa']
}) 

print('Original Dataframe: ')
print(users)

print('\nExcluding `Montreal` in using isin and stack them: ')
print(users[~users.isin(['Montreal'])].stack())

Original Dataframe: 
    name      city
0  kevin   Toronto
1  james  Montreal
2  kumar   Calgary
3  kevin  Montreal
4  kevin  Montreal
5  james    Ottawa

Excluding `Montreal` in using isin and stack them: 
0  name      kevin
   city    Toronto
1  name      james
2  name      kumar
   city    Calgary
3  name      kevin
4  name      kevin
5  name      james
   city     Ottawa
dtype: object


**Finding specific items by using `isin` function**

In [ ]:
users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa']
}) 

print('Original Dataframe: ')
print(users)

print('\nFinding `Montreal` in using isin and stack them: ')
print(users[users.isin(['Montreal'])].stack())

Original Dataframe: 
    name      city
0  kevin   Toronto
1  james  Montreal
2  kumar   Calgary
3  kevin  Montreal
4  kevin  Montreal
5  james    Ottawa

Finding `Montreal` in using isin and stack them: 
1  city    Montreal
3  city    Montreal
4  city    Montreal
dtype: object


**Match with isin function**

In [ ]:
users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa']
}) 

print('Original Dataframe:')
print(users)

print('\nFinding `Montreal` in by using isin function :')

users.isin(['Montreal']).any()

Original Dataframe:
    name      city
0  kevin   Toronto
1  james  Montreal
2  kumar   Calgary
3  kevin  Montreal
4  kevin  Montreal
5  james    Ottawa

Finding `Montreal` in by using isin function :


name    False
city     True
dtype: bool

**Change columns**

In [ ]:
users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa']
}) 

print('Before changing columns : ')
print(users)

# change columns
users_new = users.rename({'name': 'first_name', 'city': 'current_city'}, axis = 1)

print('\nAfter changing columns : ')
print(users_new)

Before changing columns : 
    name      city
0  kevin   Toronto
1  james  Montreal
2  kumar   Calgary
3  kevin  Montreal
4  kevin  Montreal
5  james    Ottawa

After changing columns : 
  first_name current_city
0      kevin      Toronto
1      james     Montreal
2      kumar      Calgary
3      kevin     Montreal
4      kevin     Montreal
5      james       Ottawa


**Change the order of columns**

In [ ]:
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users2 = users.reindex(columns=['city', 'id', 'count'])
print(users2)

   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
       city  id  count
0   Toronto   1      7
1  Montreal   1      8
2   Calgary   2      9
3  Montreal   2      2
4  Montreal   3      7
5    Ottawa   3      8


**Drop multiple rows**

In [ ]:
numbers = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6], 
    "number": [10, 20, 30, 30, 23, 12]
    
})  
print(numbers)
numbers.drop(numbers.index[[0, 3, 5]], inplace=True)
print(numbers)

   id  number
0   1      10
1   2      20
2   3      30
3   4      30
4   5      23
5   6      12
   id  number
1   2      20
2   3      30
4   5      23


**Drop multiple rows by row name**

In [ ]:
numbers = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6], 
    "number": [10, 20, 30, 30, 23, 12]
    
}, index=['one', 'two', 'three', 'four', 'five', 'six'])  
print(numbers)
numbers1 = numbers.drop(['two','six'])
print(numbers1)
numbers2 = numbers.drop('two')
print(numbers2)

       id  number
one     1      10
two     2      20
three   3      30
four    4      30
five    5      23
six     6      12
       id  number
one     1      10
three   3      30
four    4      30
five    5      23
       id  number
one     1      10
three   3      30
four    4      30
five    5      23
six     6      12


**Get group**

In [ ]:
cats = animals_df.groupby(['animal']).get_group('cat')
print(cats)

**Get the the odd row**

In [ ]:
import numpy
x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]


**Get the even columns**

In [ ]:
x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[:, 1::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


**Odd rows and even columns**

In [ ]:
x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[::2, 1::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 2  4]
 [12 14]]


**Drop duplicates**

In [ ]:
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users.drop_duplicates('id', inplace=True)
print(users)

   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
   id      city  count
0   1   Toronto      7
2   2   Calgary      9
4   3  Montreal      7


**Drop all duplicates**

In [ ]:
users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users.drop_duplicates('name', inplace=True, keep='last')
print(users)
users1 = users.drop_duplicates('name', keep=False)
print(users1)

    name      city  count
0  kevin   Toronto      7
1  james  Montreal      8
2  kumar   Calgary      9
3  kevin  Montreal      2
4  kevin  Montreal      7
5  james    Ottawa      8
    name      city  count
2  kumar   Calgary      9
4  kevin  Montreal      7
5  james    Ottawa      8
    name      city  count
2  kumar   Calgary      9
4  kevin  Montreal      7
5  james    Ottawa      8


**Basic group by**

In [ ]:
animals_df1 = animals_df.groupby('animal').apply(lambda x: x['size'][x['weight'].idxmax()])
print(animals_df1)

**Make A'th 3rd coulmn Nan**

In [ ]:
df = pd.DataFrame(np.random.randn(6,1), index=pd.date_range('2013-08-01', periods=6, freq='B'), columns=list('A'))
print(df)
df.loc[df.index[3], 'A'] = np.nan
print(df)

                   A
2013-08-01  1.764052
2013-08-02  0.400157
2013-08-05  0.978738
2013-08-06  2.240893
2013-08-07  1.867558
2013-08-08 -0.977278
                   A
2013-08-01  1.764052
2013-08-02  0.400157
2013-08-05  0.978738
2013-08-06       NaN
2013-08-07  1.867558
2013-08-08 -0.977278


**Reindex**

In [ ]:
df1 = df.reindex(df.index[::-1]).ffill()
print(df1)

                   A
2013-08-08 -0.977278
2013-08-07  1.867558
2013-08-06  1.867558
2013-08-05  0.978738
2013-08-02  0.400157
2013-08-01  1.764052


**Pandas to list**

In [ ]:
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list1 = list(employees.columns.values) 
employees_list2 = employees.values.tolist()
#employees_list = list(employees)
print(employees_list1)
print(employees_list2)

   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
['age', 'salary', 'grade', 'group']
[[17, 75, 7, 1], [50, 33, 8, 1], [24, 90, 9, 2], [45, 175, 2, 2], [65, 134, 7, 2], [18, 78, 8, 1]]


**Pandas rows to list**

In [ ]:
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = employees.values.tolist()
print(employees_list2)
print(type(employees_list2))
print(len(employees_list2))

   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
[[17, 75, 7, 1], [50, 33, 8, 1], [24, 90, 9, 2], [45, 175, 2, 2], [65, 134, 7, 2], [18, 78, 8, 1]]
<class 'list'>
6


**Pandas rows to array**

In [ ]:
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = employees.values
print(employees_list2)
print(type(employees_list2))
print(employees_list2.shape)

   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
[[ 17  75   7   1]
 [ 50  33   8   1]
 [ 24  90   9   2]
 [ 45 175   2   2]
 [ 65 134   7   2]
 [ 18  78   8   1]]
<class 'numpy.ndarray'>
(6, 4)


**Pandas rows to map**

In [ ]:
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = map(list, employees.values)
print(employees_list2)
print(type(employees_list2))

   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
<class 'map'>


**Pandas rows to map**

In [ ]:
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = list(map(list, employees.values))
print(employees_list2)
print(type(employees_list2))

   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
[[17, 75, 7, 1], [50, 33, 8, 1], [24, 90, 9, 2], [45, 175, 2, 2], [65, 134, 7, 2], [18, 78, 8, 1]]
<class 'list'>


**Selecting multiple columns**

In [ ]:
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users1 = users[['id', 'city']]
print(users1)

   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
   id      city
0   1   Toronto
1   1  Montreal
2   2   Calgary
3   2  Montreal
4   3  Montreal
5   3    Ottawa


**Selecting multiple columns**

In [ ]:
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
}) 
print(users)
columns = ['id', 'count']
users1 = pd.DataFrame(users, columns=columns)
print(users1)

   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
   id  count
0   1      7
1   1      8
2   2      9
3   2      2
4   3      7
5   3      8


**Row and Column Slicing**

In [ ]:
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
users1 = users.iloc[0:2, 1:3]
print(users1)

   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
       city  count
0   Toronto      7
1  Montreal      8


**Iterating rows**

In [ ]:
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for index, row in users.iterrows():
    print(row['city'], "==>", row['count'])

   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
Toronto ==> 7
Montreal ==> 8
Calgary ==> 9
Montreal ==> 2
Montreal ==> 7
Ottawa ==> 8


**Iterating tuples**

In [ ]:
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for row in users.itertuples(index=True, name='Pandas'):
    print(getattr(row, 'city'))
    
for row in users.itertuples(index=True, name='Pandas'):
    print(row.count)

   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
Toronto
Montreal
Calgary
Montreal
Montreal
Ottawa
7
8
9
2
7
8


**Iterating rows and columns**

In [ ]:
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for i, row in users.iterrows():
    for j, col in row.iteritems():    
        print(col)

   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
1
Toronto
7
1
Montreal
8
2
Calgary
9
2
Montreal
2
3
Montreal
7
3
Ottawa
8


**List of Dictionary to Dataframe**

In [ ]:
pointlist = [
                {'points': 50, 'time': '5:00', 'year': 2010}, 
                {'points': 25, 'time': '6:00', 'month': "february"}, 
                {'points':90, 'time': '9:00', 'month': 'january'}, 
                {'points_h1':20, 'month': 'june'}
            ]
print(pointlist)
pointDf = pd.DataFrame(pointlist)
print(pointDf)

pointDf1 = pd.DataFrame.from_dict(pointlist)
print(pointDf1)

[{'points': 50, 'time': '5:00', 'year': 2010}, {'points': 25, 'time': '6:00', 'month': 'february'}, {'points': 90, 'time': '9:00', 'month': 'january'}, {'points_h1': 20, 'month': 'june'}]
   points  time    year     month  points_h1
0    50.0  5:00  2010.0       NaN        NaN
1    25.0  6:00     NaN  february        NaN
2    90.0  9:00     NaN   january        NaN
3     NaN   NaN     NaN      june       20.0
   points  time    year     month  points_h1
0    50.0  5:00  2010.0       NaN        NaN
1    25.0  6:00     NaN  february        NaN
2    90.0  9:00     NaN   january        NaN
3     NaN   NaN     NaN      june       20.0


**NaN values**

In [ ]:
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
df1 = df.isnull()
print(df1)

          0         1         2         3         4         5
0  0.217990  0.446116 -0.819062 -1.352324 -0.763532 -0.960236
1 -0.922719       NaN -0.334374  1.858551  1.259664 -1.129287
2 -0.164548       NaN  1.177197  0.200236  0.901230  0.107576
3  1.320939  0.769797  0.108104  0.113736 -0.558491  1.342673
4 -0.368223 -0.461297  1.076169 -1.038262 -1.454537  0.339280
5  0.293486  0.875644 -0.918129       NaN  0.463781 -0.513731
6 -1.635774 -1.416454 -1.262524  0.495890 -1.447153  0.385738
7  0.044075  1.086185 -0.888498  0.911366  0.554206       NaN
8 -0.455476  0.161883  0.670322 -0.002011  1.131631       NaN
9 -0.012585  1.077887 -0.332956  1.145893 -1.885006 -0.370889
       0      1      2      3      4      5
0  False  False  False  False  False  False
1  False   True  False  False  False  False
2  False   True  False  False  False  False
3  False  False  False  False  False  False
4  False  False  False  False  False  False
5  False  False  False   True  False  False
6  False  

**Sum of all nan**

In [ ]:
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum())
print(df.isnull().sum(axis=1))
print(df.isnull().sum().tolist())

          0         1         2         3         4         5
0  2.088563  0.231459 -1.251079  0.704646 -1.166442  0.448813
1 -0.171223       NaN  1.734200 -2.025169 -1.147663 -0.680795
2 -1.342513       NaN  0.193023 -0.237307 -0.482156 -0.134534
3  0.669996 -0.793702 -0.387130  0.392890 -0.788523  0.537616
4  1.474900 -0.596172 -0.063693 -1.240504 -1.834939  0.629844
5  1.131971 -0.003096 -1.553394       NaN -0.965569 -1.257372
6  0.503083  0.092577  0.395931 -1.888212 -0.373666  2.131113
7 -0.892120  0.460762 -0.969789  0.007106  1.717064       NaN
8  0.362164  1.210222 -2.550062  0.482174  0.342836       NaN
9  1.190521  0.848214  0.303314  0.919155  1.578715  1.771569
0    0
1    2
2    0
3    1
4    0
5    2
dtype: int64
0    0
1    1
2    1
3    0
4    0
5    1
6    0
7    1
8    1
9    0
dtype: int64
[0, 2, 0, 1, 0, 2]


**Sum of all nan rowwise**

In [ ]:
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum(axis=1))

          0         1         2         3         4         5
0 -0.440883 -0.157030  0.087852  1.022063  1.114579 -0.038081
1 -1.601161       NaN -0.541547  1.507458  0.290414 -2.819083
2  0.462185       NaN  1.311486 -0.873955 -0.749647  0.815721
3  0.491506  0.088078  0.405965  1.882544 -1.475927 -1.116513
4 -1.443477  0.449824 -0.353926  1.321172 -0.160297  0.596804
5  0.423406 -0.928333 -2.623462       NaN  0.504588  0.401967
6 -0.273848  0.031379  1.992330 -0.849768 -0.464734  0.179325
7 -1.375814  1.536620 -0.387260 -1.290004  0.466924       NaN
8  0.754603  0.555904  0.189276 -0.426599  0.035094       NaN
9 -1.633910  1.409222 -0.423086 -0.302064 -0.912152 -0.871047
0    0
1    1
2    1
3    0
4    0
5    1
6    0
7    1
8    1
9    0
dtype: int64


**Sum of all nan as list**

In [ ]:
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum().tolist())

          0         1         2         3         4         5
0  1.303152 -0.609694 -0.443278 -0.646600 -0.474094 -0.203608
1 -1.751956       NaN  1.571051 -0.155592  0.773396  2.219493
2  1.925418       NaN  1.145302 -1.860705 -1.043996  2.652211
3 -1.553704 -0.102464  0.669496  0.445226  0.042220 -1.996937
4  1.120190  2.681242  1.148746 -0.541898  0.346474  0.805443
5  0.053541 -1.086637  1.173338       NaN -0.291910 -0.993342
6  1.182458 -1.398676  0.997795 -0.902583 -0.285639 -0.078916
7 -0.447757 -0.757681 -2.784148  0.203487  0.523540       NaN
8 -1.058292 -1.538603  1.347284 -0.417725  0.288348       NaN
9 -0.787049 -0.919619 -0.097892  0.053204  0.921805  1.064299
[0, 2, 0, 1, 0, 2]


**Change the order of columns**

In [ ]:
#'.reindex_axis' is deprecated and will be removed in a future version
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users2 = users.reindex(columns=['city', 'id', 'count'])
print(users2)

   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
       city  id  count
0   Toronto   1      7
1  Montreal   1      8
2   Calgary   2      9
3  Montreal   2      2
4  Montreal   3      7
5    Ottawa   3      8


**Drop multiple rows**

In [ ]:
numbers = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6], 
    "number": [10, 20, 30, 30, 23, 12]
    
})  
print(numbers)
numbers.drop(numbers.index[[0, 3, 5]], inplace=True)
print(numbers)

   id  number
0   1      10
1   2      20
2   3      30
3   4      30
4   5      23
5   6      12
   id  number
1   2      20
2   3      30
4   5      23


**Drop multiple rows by row name**

In [ ]:
numbers = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6], 
    "number": [10, 20, 30, 30, 23, 12]
    
}, index=['one', 'two', 'three', 'four', 'five', 'six'])  
print(numbers)
numbers1 = numbers.drop(['two','six'])
print(numbers1)
numbers2 = numbers.drop('two')
print(numbers2)

**Create Numpy Array Create three columns with Zero values**

In [ ]:
dtype = [('Col1','int32'), ('Col2','float32'), ('Col3','float32')]
values = np.zeros(20, dtype=dtype)
index = ['Row'+str(i) for i in range(1, len(values)+1)]

df = pd.DataFrame(values, index=index)
print(df)

df = pd.DataFrame(values)
print(df)

       Col1  Col2  Col3
Row1      0   0.0   0.0
Row2      0   0.0   0.0
Row3      0   0.0   0.0
Row4      0   0.0   0.0
Row5      0   0.0   0.0
Row6      0   0.0   0.0
Row7      0   0.0   0.0
Row8      0   0.0   0.0
Row9      0   0.0   0.0
Row10     0   0.0   0.0
Row11     0   0.0   0.0
Row12     0   0.0   0.0
Row13     0   0.0   0.0
Row14     0   0.0   0.0
Row15     0   0.0   0.0
Row16     0   0.0   0.0
Row17     0   0.0   0.0
Row18     0   0.0   0.0
Row19     0   0.0   0.0
Row20     0   0.0   0.0
    Col1  Col2  Col3
0      0   0.0   0.0
1      0   0.0   0.0
2      0   0.0   0.0
3      0   0.0   0.0
4      0   0.0   0.0
5      0   0.0   0.0
6      0   0.0   0.0
7      0   0.0   0.0
8      0   0.0   0.0
9      0   0.0   0.0
10     0   0.0   0.0
11     0   0.0   0.0
12     0   0.0   0.0
13     0   0.0   0.0
14     0   0.0   0.0
15     0   0.0   0.0
16     0   0.0   0.0
17     0   0.0   0.0
18     0   0.0   0.0
19     0   0.0   0.0


**iLoc in Pandas|Print first five rows**

In [ ]:
print(df.iloc[:4]) 

**Create Random integer between 2 to 10 with 4 items**

In [ ]:
values = np.random.randint(2, 10, size=4)
print(values)

[3 7 9 8]


**Create Random integer between 0 to 100**

In [ ]:
df = pd.DataFrame(np.random.randint(0, 100, size=(3, 2)), columns=list('xy'))
print(df)

    x   y
0   8  29
1  71  64
2  78  30


**Create Random integer between 2 to 10 with 4 columns**

In [ ]:
df = pd.DataFrame(np.random.randint(0, 100, size=(2, 4)), columns=['A', 'B', 'C', 'D'])
print(df)

    A   B   C   D
0  12   3  36  36
1  35  24  50  79


**2D array with random between 0 and 5**

In [ ]:
values = np.random.randint(5, size=(2, 4))
print(values)
print(type(values))

[[2 4 4 3]
 [3 4 0 3]]
<class 'numpy.ndarray'>


**Create Random integer between 0 to 100 with 10 itmes (2 rows, 5 columns)**

In [ ]:
df = pd.DataFrame(np.random.randint(0, 100, size=(3, 5)), columns=['Toronto', 'Ottawa', 'Calgary', 'Montreal', 'Quebec'])
print(df)

   Toronto  Ottawa  Calgary  Montreal  Quebec
0       69      65       58        85      83
1       33      83        8        84      12
2       42      69       37        35       3


**First 4 rows and 2 columns of CSV**

In [ ]:
print(df.iloc[0:4,0:2])

**Show even rows and first three columns**

In [ ]:
print(df.iloc[::2, 0:3])  

**New columns as sum of all**

In [ ]:
df['total'] = df.sum(axis=1)

**Delete Rows of one column where the value is less than 50**

In [ ]:
df = df[df.science > 50]

**Delete with Query**

In [ ]:
df = df.query('science > 45')

**Skip single row**

In [ ]:
df = pandas.read_csv('/kaggle/input/datasets-for-pandas/abc.csv', sep=',', encoding = "utf-8", skiprows=[5])

**Skip multiple rows**

In [ ]:
df = pandas.read_csv('/kaggle/input/datasets-for-pandas/abc.csv', sep=',', encoding = "utf-8", skiprows=[1, 5, 7])

**Select Column by Index**

In [ ]:
df = pandas.read_csv('/kaggle/input/datasets-for-pandas/abc.csv', sep=',', encoding = "utf-8")
#df = df[int(df.columns[2]) > 45]
print(df)
print(type(df.columns[2]))

**Skip rows**

In [ ]:
df = pandas.read_csv('/kaggle/input/datasets-for-pandas/abc.csv', sep=',', encoding = "utf-8", skiprows=[0])
#df = df[int(df.columns[2]) > 45]
#print(df)
print(df.columns[2])

**String to Dataframe**

In [ ]:
print('Task 22:')
from io import StringIO

s = """
        1, 2
        3, 4
        5, 6
    """

df = pd.read_csv(StringIO(s), header=None)

print(df.shape)
print(df)

Task 22:
(3, 2)
   0  1
0  1  2
1  3  4
2  5  6


**New columns as max of other columns**

In [ ]:
df = pandas.read_csv('/kaggle/input/datasets-for-pandas/abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
df['sum'] = df.sum(axis=1)
df['max'] = df.max(axis=1)
df['min'] = df.min(axis=1)
df['average'] = df.mean(axis=1).astype(int)
print(df)

In [ ]:
def apply_math_special(row):
    return (row.maths * 2 + row.language / 2 + row.history / 3 + row.science) / 4                

print('Task 24:') 
df = pandas.read_csv('/kaggle/input/datasets-for-pandas/abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
df['sum'] = df.sum(axis=1)
df['max'] = df.max(axis=1)
df['min'] = df.min(axis=1)
df['average'] = df.mean(axis=1).astype(int)
df['math_special'] = df.apply(apply_math_special, axis=1).astype(int)
print(df)

In [ ]:
#New columns as max of other columns
#35 marks considered as pass
#If the student fails in math, consider fail
#If the student passes in language and science, consider as pass

def pass_one_subject(row):
    if(row.maths > 34):
        return 'Pass'
    if(row.language > 34 and row.science > 34):
        return 'Pass'
    
    return 'Fail'                

df = pandas.read_csv('/kaggle/input/datasets-for-pandas/abc.csv', sep=',', encoding = "utf-8")
print(df.shape)   

df['pass_one'] = df.apply(pass_one_subject, axis=1)
print(df)

**Fill with average**

In [ ]:
df.fillna(df.mean(), inplace=True)

**New columns as sum of all**

In [ ]:
df = pd.DataFrame(np.random.rand(10, 5))
df.iloc[0:3, 0:4] = np.nan # throw in some na values
print(df)
df.loc[:, 'test'] = df.iloc[:, 2:].sum(axis=1)
print(df)

          0         1         2         3         4
0       NaN       NaN       NaN       NaN  0.088910
1       NaN       NaN       NaN       NaN  0.381285
2       NaN       NaN       NaN       NaN  0.930471
3  0.636566  0.640584  0.673207  0.507055  0.788924
4  0.723285  0.217202  0.789462  0.046728  0.915531
5  0.414056  0.427601  0.313134  0.823060  0.529835
6  0.383649  0.041548  0.312690  0.057411  0.066345
7  0.933612  0.862219  0.158193  0.575282  0.104705
8  0.909829  0.543992  0.205456  0.142440  0.864909
9  0.180093  0.568493  0.516203  0.551560  0.651241
          0         1         2         3         4      test
0       NaN       NaN       NaN       NaN  0.088910  0.088910
1       NaN       NaN       NaN       NaN  0.381285  0.381285
2       NaN       NaN       NaN       NaN  0.930471  0.930471
3  0.636566  0.640584  0.673207  0.507055  0.788924  1.969187
4  0.723285  0.217202  0.789462  0.046728  0.915531  1.751721
5  0.414056  0.427601  0.313134  0.823060  0.529835  1.6

**Last 4 rows**

In [ ]:
print(df[-4:])

**Expanding Apply**

In [ ]:
series1 = pd.Series([i / 100.0 for i in range(1,6)])
print(series1)
def CumRet(x,y):
    return x * (1 + y)
def Red(x):
    return functools.reduce(CumRet,x,1.0)
s2 = series1.expanding().apply(Red)
# s2 = series1.expanding().apply(Red, raw=True) # is not working
print(s2)

0    0.01
1    0.02
2    0.03
3    0.04
4    0.05
dtype: float64
0    1.010000
1    1.030200
2    1.061106
3    1.103550
4    1.158728
dtype: float64


**Get 3 and 4th row**

In [ ]:
print(df[2:4])

**Last 4th to 1st**

In [ ]:
print(df[-4:-1])

**iloc position slice**

In [ ]:
print(df.iloc[1:9])

**Filter with the value comparison**

In [ ]:
below_20 = data[data['rnd_1'] < 20] 
ten_to_20 = data[(data['rnd_1'] >= 5) & (data['rnd_1'] < 10)]
ten_to_20 = data[(data['rnd_1'] >= 15) & (data['rnd_1'] < 20)]
ten_to_20 = data[(data['rnd_1 '] >= 15) & (data['rnd_1'] < 33)]

**Custom method and xrnage on dataframe**

In [ ]:
filter_loc = data.loc[ 2 : 4 ,  [ 'rnd_2' ,  'date' ]]
print(filter_loc)

**Set index with date column**

In [ ]:
date_date = data.set_index( 'date' ) 

**Change columns based on other columns**

In [ ]:
df = pd.DataFrame({
    'a' : [1,2,3,4], 
    'b' : [9,8,7,6],
    'c' : [11,12,13,14]
})
print(df) 

print('changing on one column')
# Change columns
df.loc[df.a >= 2,'b'] = 9
print(df)

   a  b   c
0  1  9  11
1  2  8  12
2  3  7  13
3  4  6  14
changing on one column
   a  b   c
0  1  9  11
1  2  9  12
2  3  9  13
3  4  9  14


**Change multiple columns based on one column values**

In [ ]:
print('changing on multipe columns')
df.loc[df.a > 2,['b', 'c']] = 45
print(df)

changing on multipe columns
   a   b   c
0  1   9  11
1  2   9  12
2  3  45  45
3  4  45  45


**Pandas Mask**

In [ ]:
print(df)
df_mask = pd.DataFrame({
    'a' : [True] * 4, 
    'b' : [False] * 4,
    'c' : [True, False] * 2
})
print(df.where(df_mask,-1000))

   a   b   c
0  1   9  11
1  2   9  12
2  3  45  45
3  4  45  45
   a     b     c
0  1 -1000    11
1  2 -1000 -1000
2  3 -1000    45
3  4 -1000 -1000


**Check high or low comparing the column against 5**

In [ ]:
df['logic'] = np.where(df['a'] > 5, 'high', 'low')

**iloc with positional slicing**

In [ ]:
print(stars_df.iloc[1:3])

**Label between numbers**

In [ ]:
numbers = pd.DataFrame({
        'one' : [10, 50, 80, 40],
        'two' : [2, 6, 56, 45]
    },
    index = [12, 14, 16, 18])
print(numbers)

print('label between 12 and 16')
print(numbers.loc[12:16])

print('index between 1 and 3')
print(numbers.iloc[1:3])

**Inverse opeartor!( above one.45 and below two.50 )**

In [ ]:
print(numbers[~( (numbers.one > 45) & (numbers.two < 50) )])

**Delete by pop function**

In [2]:
import pandas as pd
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)
group = employees.pop('group')
print(employees)
print(group)

   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
0    1
1    1
2    2
3    2
4    2
5    1
Name: group, dtype: int64


**Drop first and last column**

In [3]:
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)
employees.drop(employees.columns[[0, len(employees.columns)-1]], axis=1, inplace = True)
print(employees)

   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
   salary  grade
0      75      7
1      33      8
2      90      9
3     175      2
4     134      7
5      78      8


**Drop multiple columns**

In [5]:
import numpy as np
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)
employees.drop(employees.columns[[1, 2]], axis=1, inplace = True)
print(employees)

   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   age  salary  grade     group
0   17      75      7 -0.009268
1   50      33      8 -1.215387
2   24      90      9  0.272814
3   45     175      2  0.771399
4   65     134      7  0.058326
5   18      78      8  0.583762
   age     group
0   17 -0.009268
1   50 -1.215387
2   24  0.272814
3   45  0.771399
4   65  0.058326
5   18  0.583762


**Drop a column**

In [6]:
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)
employees.drop(employees.columns[[0]], axis=1, inplace = True)
print(employees)

   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   age  salary  grade     group
0   17      75      7  0.858804
1   50      33      8 -0.761004
2   24      90      9 -1.240335
3   45     175      2 -2.557449
4   65     134      7 -0.422497
5   18      78      8  0.903855
   salary  grade     group
0      75      7  0.858804
1      33      8 -0.761004
2      90      9 -1.240335
3     175      2 -2.557449
4     134      7 -0.422497
5      78      8  0.903855


**Add a new column**

In [7]:
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)

   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   age  salary  grade     group
0   17      75      7 -2.132891
1   50      33      8  0.939560
2   24      90      9  1.568289
3   45     175      2 -0.113816
4   65     134      7 -0.996404
5   18      78      8 -0.016030


**Rename columns**

In [8]:
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees.rename(columns={'age': 'User Age', 'salary': 'Salary 2018'}, inplace=True)
print(employees)

   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   User Age  Salary 2018  grade
0        17           75      7
1        50           33      8
2        24           90      9
3        45          175      2
4        65          134      7
5        18           78      8
